-- VHDL Entity tb_lib.basic_test_case.symbol
--
-- Created:
--          by - kayra.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 09:47:59 10/08/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY basic_test_case IS
   PORT( 
      clk           : IN     std_logic;
      rst_n         : IN     std_logic;
      alien_x_basic : OUT    std_logic_vector (7 DOWNTO 0);
      btn           : OUT    std_logic;
      done_basic    : OUT    std_logic;
      gun_x         : OUT    std_logic_vector (7 DOWNTO 0);
      ref_basic     : OUT    std_logic
   );

-- Declarations

END basic_test_case ;

--
-- VHDL Architecture tb_lib.basic_test_case.fsm
--
-- Created:
--          by - kayra.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 09:47:59 10/08/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF basic_test_case IS

   -- Architecture Declarations
   SIGNAL pressed : std_logic;  
   SIGNAL ref_hit_done : std_logic;  

   TYPE STATE_TYPE IS (
      all_tested,
      end_timer,
      test,
      reset,
      var_alien,
      var_b_x,
      do_hit,
      start_wait,
      s0
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(4 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(4 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_end_timer : std_logic;
   SIGNAL csm_to_start_wait : std_logic;

   -- Declare any pre-registered internal signals
   SIGNAL alien_x_basic_cld : std_logic_vector (7 DOWNTO 0);
   SIGNAL btn_cld : std_logic ;
   SIGNAL done_basic_cld : std_logic ;
   SIGNAL gun_x_cld : std_logic_vector (7 DOWNTO 0);
   SIGNAL ref_basic_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= reset;
         csm_timer <= (OTHERS => '0');
         -- Default Reset Values
         alien_x_basic_cld <= "00010000";
         btn_cld <= '0';
         done_basic_cld <= '0';
         gun_x_cld <= "10000000";
         ref_basic_cld <= '0';
         pressed <= '0';
         ref_hit_done <= '0';
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;

         -- Combined Actions
         CASE current_state IS
            WHEN all_tested => 
               done_basic_cld <='1';
            WHEN test => 
               ref_basic_cld<='0';
               btn_cld<='0';
            WHEN var_alien => 
               gun_x_cld <="00000001";
               alien_x_basic_cld<=alien_x_basic_cld(6 downto 0) & '0';
               ref_hit_done<='0';
               pressed<='0';
            WHEN var_b_x => 
               gun_x_cld<=gun_x_cld(6 downto 0) & '0';
               ref_hit_done<='0';
               pressed<='0';
            WHEN do_hit => 
               ref_hit_done<='1';
               ref_basic_cld<='1';
               btn_cld<='0';
            WHEN start_wait => 
               IF (csm_timeout = '1') THEN 
                  alien_x_basic_cld<="00000001";
                  gun_x_cld<="00000001";
               END IF;
            WHEN s0 => 
               pressed<='1';
               btn_cld<='1';
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      alien_x_basic_cld,
      csm_timeout,
      current_state,
      gun_x_cld,
      pressed,
      ref_hit_done
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_end_timer <= '0';
      csm_to_start_wait <= '0';
      CASE current_state IS
         WHEN all_tested => 
            next_state <= all_tested;
         WHEN end_timer => 
            IF (csm_timeout = '1') THEN 
               next_state <= all_tested;
            ELSE
               next_state <= end_timer;
            END IF;
         WHEN test => 
            IF (alien_x_basic_cld="00000000") THEN 
               next_state <= end_timer;
               csm_to_end_timer <= '1';
            ELSIF (pressed='0') THEN 
               next_state <= s0;
            ELSIF (gun_x_cld="00000000") THEN 
               next_state <= var_alien;
            ELSE
               next_state <= var_b_x;
            END IF;
         WHEN reset => 
            next_state <= start_wait;
            csm_to_start_wait <= '1';
         WHEN var_alien => 
            next_state <= test;
         WHEN var_b_x => 
            next_state <= test;
         WHEN do_hit => 
            next_state <= test;
         WHEN start_wait => 
            IF (csm_timeout = '1') THEN 
               next_state <= test;
            ELSE
               next_state <= start_wait;
            END IF;
         WHEN s0 => 
            IF (alien_x_basic_cld/="00000000" and 
                alien_x_basic_cld=gun_x_cld and
                ref_hit_done='0') THEN 
               next_state <= do_hit;
            ELSE
               next_state <= test;
            END IF;
         WHEN OTHERS =>
            next_state <= reset;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_end_timer,
      csm_to_start_wait
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_end_timer = '1') THEN
         csm_next_timer <= "10011"; -- no cycles(20)-1=19
      ELSIF (csm_to_start_wait = '1') THEN
         csm_next_timer <= "00010"; -- no cycles(3)-1=2
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

   -- Concurrent Statements
   -- Clocked output assignments
   alien_x_basic <= alien_x_basic_cld;
   btn <= btn_cld;
   done_basic <= done_basic_cld;
   gun_x <= gun_x_cld;
   ref_basic <= ref_basic_cld;
END fsm;
