-- VHDL Entity tb_lib.gamma_set_tester.symbol
--
-- Created:
--          by - kayra
--          at - 11:11:26 10/11/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY gamma_set_tester IS
   PORT( 
      bit         : IN     std_logic;
      sb          : IN     std_logic;
      tx          : IN     std_logic;
      clk         : OUT    std_logic;
      gamma_value : OUT    std_logic_vector (5 DOWNTO 0);
      rst_n       : OUT    std_logic;
      rx_rdy      : OUT    std_logic
   );

-- Declarations

END gamma_set_tester ;

--
-- VHDL Architecture tb_lib.gamma_set_tester.struct
--
-- Created:
--          by - kayra
--          at - 11:11:26 10/11/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF gamma_set_tester IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL reg_set : std_logic_vector(5 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL clk_internal   : std_logic;
   SIGNAL rst_n_internal : std_logic;


   -- Component Declarations
   COMPONENT gamma_sequence_receiver
   PORT (
      BIT         : IN     std_logic;
      clk         : IN     std_logic;
      rst_n       : IN     std_logic;
      sb          : IN     std_logic;
      tx          : IN     std_logic;
      gamma_value : OUT    std_logic_vector (5 DOWNTO 0);
      reg_set     : OUT    std_logic_vector (5 DOWNTO 0);
      run         : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT gamma_test_block
   PORT (
      reg_set : IN     std_logic_vector (5 DOWNTO 0);
      sb      : IN     std_logic;
      clk     : OUT    std_logic;
      rst_n   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : gamma_sequence_receiver USE ENTITY tb_lib.gamma_sequence_receiver;
   FOR ALL : gamma_test_block USE ENTITY tb_lib.gamma_test_block;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : gamma_sequence_receiver
      PORT MAP (
         BIT         => bit,
         clk         => clk_internal,
         rst_n       => rst_n_internal,
         tx          => tx,
         run         => rx_rdy,
         sb          => sb,
         reg_set     => reg_set,
         gamma_value => gamma_value
      );
   U_0 : gamma_test_block
      PORT MAP (
         clk     => clk_internal,
         rst_n   => rst_n_internal,
         sb      => sb,
         reg_set => reg_set
      );

   -- Implicit buffered output assignments
   clk   <= clk_internal;
   rst_n <= rst_n_internal;

END struct;
