-- VHDL Entity tb_lib.tb_alien.symbol
--
-- Created:
--          by - kayra
--          at - 11:00:44 05/31/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_alien IS
-- Declarations

END tb_alien ;

--
-- VHDL Architecture tb_lib.tb_alien.struct
--
-- Created:
--          by - kayra
--          at - 13:25:56 09/20/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_alien IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alien_defeated : std_logic;
   SIGNAL alien_hp       : std_logic_vector(3 DOWNTO 0);
   SIGNAL alien_x        : std_logic_vector(7 DOWNTO 0);
   SIGNAL alien_y        : std_logic_vector(7 DOWNTO 0);
   SIGNAL clk            : std_logic;
   SIGNAL color          : std_logic_vector(23 DOWNTO 0);
   SIGNAL color_end      : std_logic_vector(23 DOWNTO 0);
   SIGNAL en             : std_logic;
   SIGNAL hit            : std_logic;
   SIGNAL rst_n          : std_logic;
   SIGNAL sw0            : std_logic;
   SIGNAL x_end          : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_end          : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT alien_tester
   PORT (
      alien_defeated : IN     std_logic;
      alien_hp       : IN     std_logic_vector (3 DOWNTO 0);
      color          : IN     std_logic_vector (23 DOWNTO 0);
      color_end      : IN     std_logic_vector (23 DOWNTO 0);
      x              : IN     std_logic_vector (7  DOWNTO 0);
      x_end          : IN     std_logic_vector (7 DOWNTO 0);
      y              : IN     std_logic_vector (7  DOWNTO 0);
      y_end          : IN     std_logic_vector (7 DOWNTO 0);
      clk            : OUT    std_logic;
      en             : OUT    std_logic;
      hit            : OUT    std_logic;
      rst_n          : OUT    std_logic;
      sw0            : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : alien_tester USE ENTITY tb_lib.alien_tester;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'alien_hp' of 'constval'
   alien_hp <= "0011";

   -- ModuleWare code(v1.12) for instance 'color_end' of 'constval'
   color_end <= "000000000000000000001100";

   -- ModuleWare code(v1.12) for instance 'x_end' of 'constval'
   x_end <= "00000000";

   -- ModuleWare code(v1.12) for instance 'y_end' of 'constval'
   y_end <= "00000001";

   -- Instance port mappings.
   U_1 : alien_tester
      PORT MAP (
         color          => color,
         y              => alien_y,
         x              => alien_x,
         clk            => clk,
         rst_n          => rst_n,
         sw0            => sw0,
         en             => en,
         hit            => hit,
         alien_hp       => alien_hp,
         x_end          => x_end,
         y_end          => y_end,
         color_end      => color_end,
         alien_defeated => alien_defeated
      );

END struct;
