-- VHDL Entity tb_lib.tb_gun.symbol
--
-- Created:
--          by - kayra.UNKNOWN (LAPTOP-IT04P56L)
--          at - 14:04:39 05/31/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_gun IS
-- Declarations

END tb_gun ;

--
-- VHDL Architecture tb_lib.tb_gun.struct
--
-- Created:
--          by - Asus.UNKNOWN (LAPTOP-IT04P56L)
--          at - 13:59:51 05/29/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_gun IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL btn              : std_logic_vector(3 DOWNTO 0);
   SIGNAL clk              : std_logic;
   SIGNAL enable           : std_logic;
   SIGNAL gun_color        : std_logic_vector(23 DOWNTO 0);
   SIGNAL gun_pixel_amount : std_logic_vector(4 DOWNTO 0);
   SIGNAL gun_px_idx       : std_logic_vector(4 DOWNTO 0);
   SIGNAL gun_x            : std_logic_vector(7 DOWNTO 0);
   SIGNAL gun_y            : std_logic_vector(7 DOWNTO 0);
   SIGNAL rst_n            : std_logic;


   -- Component Declarations
   COMPONENT c3_t1_gun_module
   PORT (
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic ;
      enable     : IN     std_logic ;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic ;
      gun_col    : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord    : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT gun_test_block
   PORT (
      gun_color        : IN     std_logic_vector (23 DOWNTO 0);
      gun_pixel_amount : IN     std_logic_vector (4 DOWNTO 0);
      gun_x            : IN     std_logic_vector (7 DOWNTO 0);
      gun_y            : IN     std_logic_vector (7 DOWNTO 0);
      btn              : OUT    std_logic_vector (3 DOWNTO 0);
      clk              : OUT    std_logic;
      enable           : OUT    std_logic;
      gun_px_idx       : OUT    std_logic_vector (4 DOWNTO 0);
      rst_n            : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c3_t1_gun_module USE ENTITY alien_game_lib.c3_t1_gun_module;
   FOR ALL : gun_test_block USE ENTITY tb_lib.gun_test_block;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'gun_pixel_amount' of 'constval'
   gun_pixel_amount <= "00010";

   -- Instance port mappings.
   U_1 : c3_t1_gun_module
      PORT MAP (
         btn        => btn,
         clk        => clk,
         enable     => enable,
         gun_px_idx => gun_px_idx(1 DOWNTO 0),
         rst_n      => rst_n,
         gun_col    => gun_color,
         x_coord    => gun_x,
         y_coord    => gun_y
      );
   U_0 : gun_test_block
      PORT MAP (
         clk              => clk,
         rst_n            => rst_n,
         gun_x            => gun_x,
         gun_y            => gun_y,
         gun_color        => gun_color,
         btn              => btn,
         gun_px_idx       => gun_px_idx,
         gun_pixel_amount => gun_pixel_amount,
         enable           => enable
      );

END struct;
