-- VHDL Entity tb_lib.tb_pixel_conf.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-711-SPC)
--          at - 09:38:55 07/03/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_pixel_conf IS
-- Declarations

END tb_pixel_conf ;

--
-- VHDL Architecture tb_lib.tb_pixel_conf.struct
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 03:33:18 02/15/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_pixel_conf IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color_BGR : std_logic_vector(23 DOWNTO 0);
   SIGNAL x_coord   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord   : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT constant_value
   PORT (
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT pixel_conf_tester
   PORT (
      color : IN     std_logic_vector (23 DOWNTO 0);
      x     : IN     std_logic_vector (7 DOWNTO 0);
      y     : IN     std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : constant_value USE ENTITY alien_game_lib.constant_value;
   FOR ALL : pixel_conf_tester USE ENTITY tb_lib.pixel_conf_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : constant_value
      PORT MAP (
         color_BGR => color_BGR,
         x_coord   => x_coord,
         y_coord   => y_coord
      );
   U_1 : pixel_conf_tester
      PORT MAP (
         color => color_BGR,
         x     => x_coord,
         y     => y_coord
      );

END struct;
