-- VHDL Entity tb_lib.tb_serial_tx.symbol
--
-- Created:
--          by - kayra
--          at - 14:06:14 05/31/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_serial_tx IS
-- Declarations

END tb_serial_tx ;

--
-- VHDL Architecture tb_lib.tb_serial_tx.struct
--
-- Created:
--          by - kayra
--          at - 11:31:41 10/07/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_serial_tx IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bit_in   : std_logic;
   SIGNAL clk      : std_logic;
   SIGNAL ready    : std_logic;
   SIGNAL rst_n    : std_logic;
   SIGNAL s_clk    : std_logic;
   SIGNAL s_sda    : std_logic;
   SIGNAL transmit : std_logic;


   -- Component Declarations
   COMPONENT tx_tester_struct
   PORT (
      ready    : IN     std_logic ;
      s_clk    : IN     std_logic ;
      s_sda    : IN     std_logic ;
      bit_in   : OUT    std_logic ;
      clk      : OUT    std_logic ;
      rst_n    : OUT    std_logic ;
      transmit : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : tx_tester_struct USE ENTITY tb_lib.tx_tester_struct;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : tx_tester_struct
      PORT MAP (
         ready    => ready,
         s_clk    => s_clk,
         s_sda    => s_sda,
         bit_in   => bit_in,
         clk      => clk,
         rst_n    => rst_n,
         transmit => transmit
      );

END struct;
