-- VHDL Entity alien_game_lib.c2_t2_full_adder.symbol
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-711-SPC)
--          at - 14:17:08 22.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_full_adder IS
   PORT( 
      cin   : IN     std_logic;
      sw0   : IN     std_logic;
      sw1   : IN     std_logic;
      carry : OUT    std_logic;
      sum   : OUT    std_logic
   );

-- Declarations

END c2_t2_full_adder ;

--
-- VHDL Architecture alien_game_lib.c2_t2_full_adder.struct
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-711-SPC)
--          at - 14:17:08 22.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t2_full_adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   dout1 <= dout AND cin;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout2 <= sw0 AND sw1;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or'
   carry <= dout1 OR dout2;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'xor'
   dout <= sw0 XOR sw1;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'xor'
   sum <= dout XOR cin;

   -- Instance port mappings.

END struct;
