-- VHDL Entity alien_game_lib.c2_t2_component.symbol
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-713-SPC)
--          at - 17:46:07 23.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_component IS
   PORT( 
      shift   : IN     std_logic;
      sw0     : IN     std_logic;
      sw1     : IN     std_logic;
      sw2_not : IN     std_logic;
      cout    : OUT    std_logic
   );

-- Declarations

END c2_t2_component ;

--
-- VHDL Architecture alien_game_lib.c2_t2_component.struct
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-713-SPC)
--          at - 17:46:07 23.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t2_component IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   dout1 <= sw0 AND shift;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout2 <= sw1 AND dout;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'inv'
   dout <= NOT(sw2_not);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   cout <= dout1 OR dout2;

   -- Instance port mappings.

END struct;
