-- VHDL Entity alien_game_lib.c2_t7_basic_alien_top.symbol
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 00:17:41 05/31/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_basic_alien_top IS
   PORT( 
      clk         : IN     std_logic;
      enable      : IN     std_logic;
      enable_slow : IN     std_logic;
      hit         : IN     std_logic;
      rst_n       : IN     std_logic;
      speed       : IN     std_logic;
      alien_col   : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord     : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t7_basic_alien_top ;

--
-- VHDL Architecture alien_game_lib.c2_t7_basic_alien_top.struct
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 00:17:41 05/31/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t7_basic_alien_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout : std_logic;


   -- Component Declarations
   COMPONENT c2_t7_basic_alien_color
   PORT (
      clk       : IN     std_logic ;
      hit       : IN     std_logic ;
      rst_n     : IN     std_logic ;
      alien_col : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t7_basic_alien_position
   PORT (
      clk     : IN     std_logic ;
      enable  : IN     std_logic ;
      rst_n   : IN     std_logic ;
      x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t7_basic_alien_color USE ENTITY alien_game_lib.c2_t7_basic_alien_color;
   FOR ALL : c2_t7_basic_alien_position USE ENTITY alien_game_lib.c2_t7_basic_alien_position;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(enable_slow, enable, speed)
   BEGIN
      CASE speed IS
      WHEN '0' => dout <= enable_slow;
      WHEN '1' => dout <= enable;
      WHEN OTHERS => dout <= 'X';
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.
   U_0 : c2_t7_basic_alien_color
      PORT MAP (
         clk       => clk,
         hit       => hit,
         rst_n     => rst_n,
         alien_col => alien_col
      );
   U_1 : c2_t7_basic_alien_position
      PORT MAP (
         clk     => clk,
         enable  => dout,
         rst_n   => rst_n,
         x_coord => x_coord,
         y_coord => y_coord
      );

END struct;
