-- VHDL Entity alien_game_lib.c2_t7_basic_alien_position_direction.symbol
--
-- Created:
--          by - Asus.UNKNOWN (LAPTOP-IT04P56L)
--          at - 01:11:27 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_basic_alien_position_direction IS
   PORT( 
      x_coord      : IN     std_logic_vector (7 DOWNTO 0);
      x_direct_in  : IN     std_logic;
      x_direct_out : OUT    std_logic
   );

-- Declarations

END c2_t7_basic_alien_position_direction ;

--
-- VHDL Architecture alien_game_lib.c2_t7_basic_alien_position_direction.struct
--
-- Created:
--          by - Asus.UNKNOWN (LAPTOP-IT04P56L)
--          at - 01:14:57 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t7_basic_alien_position_direction IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout3 <= x_coord(0) AND NOT(x_direct_in);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout2 <= x_coord(7) AND x_direct_in;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'inv'
   dout <= NOT(x_direct_in);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(x_direct_in, dout, dout1)
   BEGIN
      CASE dout1 IS
      WHEN '0' => x_direct_out <= x_direct_in;
      WHEN '1' => x_direct_out <= dout;
      WHEN OTHERS => x_direct_out <= 'X';
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or1'
   dout1 <= dout2 OR dout3;

   -- Instance port mappings.

END struct;
