-- VHDL Entity alien_game_lib.c2_t7_basic_alien_color.symbol
--
-- Created:
--          by - Asus.UNKNOWN (LAPTOP-IT04P56L)
--          at - 12:07:43 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_basic_alien_color IS
   PORT( 
      clk       : IN     std_logic;
      hit       : IN     std_logic;
      rst_n     : IN     std_logic;
      alien_col : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c2_t7_basic_alien_color ;

--
-- VHDL Architecture alien_game_lib.c2_t7_basic_alien_color.struct
--
-- Created:
--          by - Asus.UNKNOWN (LAPTOP-IT04P56L)
--          at - 12:07:42 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t7_basic_alien_color IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL alien_col_internal : std_logic_vector (23 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(23 DOWNTO 0) := "000000000000000000000000";


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   alien_col_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_2reg_cval <= "000000000000000000000000";
         ELSE
            mw_U_2reg_cval <= dout2;
         END IF;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   dout1 <= "011010111110011100000000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(alien_col_internal, dout1, hit)
   BEGIN
      CASE hit IS
      WHEN '0' => dout2 <= alien_col_internal;
      WHEN '1' => dout2 <= dout1;
      WHEN OTHERS => dout2 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   alien_col <= alien_col_internal;

END struct;
