-- VHDL Entity alien_game_lib.c2_t2_decrementer.symbol
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-711-SPC)
--          at - 14:07:23 22.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_decrementer IS
   PORT( 
      input_to_your_design : IN     std_logic_vector (2 DOWNTO 0);
      result               : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c2_t2_decrementer ;

--
-- VHDL Architecture alien_game_lib.c2_t2_decrementer.struct
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-711-SPC)
--          at - 14:29:02 22.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t2_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry  : std_logic;
   SIGNAL carry1 : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL dout0  : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL dout3  : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL sum    : std_logic;
   SIGNAL sum1   : std_logic;
   SIGNAL sum2   : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'split'
   SIGNAL mw_U_0temp_din : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t2_full_adder
   PORT (
      cin   : IN     std_logic ;
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t2_full_adder USE ENTITY alien_game_lib.c2_t2_full_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout <= '0';

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout1 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout5 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout3 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_1' of 'merge'
   result <= sum2 & sum1 & sum;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'split'
   mw_U_0temp_din <= input_to_your_design;
   u_0combo_proc: PROCESS (mw_U_0temp_din)
   VARIABLE temp_din: std_logic_vector(2 DOWNTO 0);
   BEGIN
      temp_din := mw_U_0temp_din(2 DOWNTO 0);
      dout0 <= temp_din(0);
      dout2 <= temp_din(1);
      dout4 <= temp_din(2);
   END PROCESS u_0combo_proc;

   -- Instance port mappings.
   U_6 : c2_t2_full_adder
      PORT MAP (
         cin   => dout,
         sw0   => dout0,
         sw1   => dout1,
         carry => carry,
         sum   => sum
      );
   U_7 : c2_t2_full_adder
      PORT MAP (
         cin   => carry,
         sw0   => dout3,
         sw1   => dout2,
         carry => carry1,
         sum   => sum1
      );
   U_8 : c2_t2_full_adder
      PORT MAP (
         cin   => carry1,
         sw0   => dout5,
         sw1   => dout4,
         carry => OPEN,
         sum   => sum2
      );

END struct;
