-- VHDL Entity alien_game_lib.c3_t4_gun_bullet.symbol
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 00:04:16 05/31/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t4_gun_bullet IS
   PORT( 
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic;
      enable         : IN     std_logic;
      gun_x_coord    : IN     std_logic_vector ( 7 DOWNTO 0);
      rst_n          : IN     std_logic;
      bullet_color   : OUT    std_logic_vector (23 DOWNTO 0);
      bullet_x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t4_gun_bullet ;

--
-- VHDL Architecture alien_game_lib.c3_t4_gun_bullet.struct
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 00:04:15 05/31/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t4_gun_bullet IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL c_out    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1    : std_logic;
   SIGNAL dout2    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout6    : std_logic_vector(23 DOWNTO 0);
   SIGNAL equality : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL bullet_x_coord_internal : std_logic_vector (7 DOWNTO 0);
   SIGNAL bullet_y_coord_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_6' of 'adff'
   SIGNAL mw_U_6reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic_vector(23 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t4_right_shifter
   PORT (
      c_in  : IN     std_logic_vector (7 DOWNTO 0);
      c_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c4_t1_coordinate_compare
   PORT (
      coord_1  : IN     std_logic_vector (7 DOWNTO 0);
      coord_2  : IN     std_logic_vector (7 DOWNTO 0);
      equality : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t4_right_shifter USE ENTITY alien_game_lib.c2_t4_right_shifter;
   FOR ALL : c4_t1_coordinate_compare USE ENTITY alien_game_lib.c4_t1_coordinate_compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   bullet_x_coord_internal <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_5reg_cval <= "00000000";
         ELSE
            mw_U_5reg_cval <= dout;
         END IF;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'adff'
   bullet_y_coord_internal <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_6reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_6reg_cval <= dout4;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'adff'
   bullet_color <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_7reg_cval <= "000000000000000000000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_7reg_cval <= dout6;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout1 <= btn(0) AND equality;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   dout3 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_11' of 'constval'
   dout5 <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   dout6 <= "000111000111000111000111";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(bullet_y_coord_internal, c_out, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout2 <= bullet_y_coord_internal;
      WHEN '1' => dout2 <= c_out;
      WHEN OTHERS => dout2 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(bullet_x_coord_internal, gun_x_coord, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => dout <= bullet_x_coord_internal;
      WHEN '1' => dout <= gun_x_coord;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(dout2, dout3, dout1)
   BEGIN
      CASE dout1 IS
      WHEN '0' => dout4 <= dout2;
      WHEN '1' => dout4 <= dout3;
      WHEN OTHERS => dout4 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- Instance port mappings.
   U_9 : c2_t4_right_shifter
      PORT MAP (
         c_in  => bullet_y_coord_internal,
         c_out => c_out
      );
   U_8 : c4_t1_coordinate_compare
      PORT MAP (
         coord_1  => dout5,
         coord_2  => bullet_y_coord_internal,
         equality => equality
      );

   -- Implicit buffered output assignments
   bullet_x_coord <= bullet_x_coord_internal;
   bullet_y_coord <= bullet_y_coord_internal;

END struct;
