-- VHDL Entity alien_game_lib.c4_t1_hit_detector.symbol
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 18:53:27 05/28/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_hit_detector IS
   PORT( 
      alien_x : IN     std_logic_vector (7 DOWNTO 0);
      alien_y : IN     std_logic_vector (7 DOWNTO 0);
      clk     : IN     std_logic;
      gun_x   : IN     std_logic_vector (7 DOWNTO 0);
      gun_y   : IN     std_logic_vector (7 DOWNTO 0);
      rst_n   : IN     std_logic;
      hit     : OUT    std_logic
   );

-- Declarations

END c4_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c4_t1_hit_detector.struct
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 18:53:27 05/28/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout      : std_logic;
   SIGNAL dout1     : std_logic;
   SIGNAL equality  : std_logic;
   SIGNAL equality1 : std_logic;
   SIGNAL q         : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic;

   -- Component Declarations
   COMPONENT c4_t1_coordinate_compare
   PORT (
      coord_1  : IN     std_logic_vector (7 DOWNTO 0);
      coord_2  : IN     std_logic_vector (7 DOWNTO 0);
      equality : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_t1_coordinate_compare USE ENTITY alien_game_lib.c4_t1_coordinate_compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   hit <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout1;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   q <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= dout;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   dout <= equality AND equality1;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout1 <= NOT(q) AND dout;

   -- Instance port mappings.
   U_4 : c4_t1_coordinate_compare
      PORT MAP (
         coord_1  => alien_x,
         coord_2  => gun_x,
         equality => equality
      );
   U_5 : c4_t1_coordinate_compare
      PORT MAP (
         coord_1  => alien_y,
         coord_2  => gun_y,
         equality => equality1
      );

END struct;
