-- VHDL Entity alien_game_lib.c4_t1_coordinate_compare.symbol
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 18:16:12 05/28/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_coordinate_compare IS
   PORT( 
      coord_1  : IN     std_logic_vector (7 DOWNTO 0);
      coord_2  : IN     std_logic_vector (7 DOWNTO 0);
      equality : OUT    std_logic
   );

-- Declarations

END c4_t1_coordinate_compare ;

--
-- VHDL Architecture alien_game_lib.c4_t1_coordinate_compare.struct
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 18:22:53 05/28/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_coordinate_compare IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;
   SIGNAL dout7 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_9' of 'and'
   equality <= dout AND dout1 AND dout2 AND dout3 AND dout4 AND dout5
               AND dout6 AND dout7;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'xnor'
   dout1 <= NOT(coord_1(1) XOR coord_2(1));

   -- ModuleWare code(v1.12) for instance 'U_2' of 'xnor'
   dout2 <= NOT(coord_1(2) XOR coord_2(2));

   -- ModuleWare code(v1.12) for instance 'U_3' of 'xnor'
   dout3 <= NOT(coord_1(3) XOR coord_2(3));

   -- ModuleWare code(v1.12) for instance 'U_4' of 'xnor'
   dout4 <= NOT(coord_1(4) XOR coord_2(4));

   -- ModuleWare code(v1.12) for instance 'U_5' of 'xnor'
   dout7 <= NOT(coord_1(7) XOR coord_2(7));

   -- ModuleWare code(v1.12) for instance 'U_6' of 'xnor'
   dout5 <= NOT(coord_2(5) XOR coord_1(5));

   -- ModuleWare code(v1.12) for instance 'U_7' of 'xnor'
   dout6 <= NOT(coord_1(6) XOR coord_2(6));

   -- ModuleWare code(v1.12) for instance 'U_8' of 'xnor'
   dout <= NOT(coord_1(0) XOR coord_2(0));

   -- Instance port mappings.

END struct;
