-- VHDL Entity alien_game_lib.c5_t4_game_top_level.symbol
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 01:22:50 05/31/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t4_game_top_level IS
   PORT( 
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      clk     : IN     std_logic;
      rst_n   : IN     std_logic;
      sw0     : IN     std_logic;
      channel : OUT    std_logic_vector (7 DOWNTO 0);
      lat     : OUT    std_logic;
      s_clk   : OUT    std_logic;
      s_rst   : OUT    std_logic;
      s_sda   : OUT    std_logic;
      sb      : OUT    std_logic
   );

-- Declarations

END c5_t4_game_top_level ;

--
-- VHDL Architecture alien_game_lib.c5_t4_game_top_level.struct
--
-- Created:
--          by - ACER.UNKNOWN (LAPTOP-PGKK1HS3)
--          at - 01:22:50 05/31/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c5_t4_game_top_level IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color         : std_logic_vector(23 DOWNTO 0);
   SIGNAL frame_written : std_logic;
   SIGNAL w_rdy         : std_logic;
   SIGNAL write_out     : std_logic;
   SIGNAL xw            : std_logic_vector(7 DOWNTO 0);
   SIGNAL yw            : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c5_t4_display_logic_top_level
   PORT (
      clk           : IN     std_logic ;
      frame_written : IN     std_logic ;
      pixd_in       : IN     std_logic_vector (23 DOWNTO 0);
      rst_n         : IN     std_logic ;
      write         : IN     std_logic ;
      xw            : IN     std_logic_vector (7  DOWNTO 0);
      yw            : IN     std_logic_vector (7  DOWNTO 0);
      channel       : OUT    std_logic_vector (7 DOWNTO 0);
      lat           : OUT    std_logic ;
      s_clk         : OUT    std_logic ;
      s_rst         : OUT    std_logic ;
      s_sda         : OUT    std_logic ;
      sb            : OUT    std_logic ;
      w_rdy         : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c5_t4_game_logic_top_level
   PORT (
      btn           : IN     std_logic_vector (3 DOWNTO 0);
      clk           : IN     std_logic ;
      rst_n         : IN     std_logic ;
      sw0           : IN     std_logic ;
      w_rdy         : IN     std_logic ;
      color         : OUT    std_logic_vector (23 DOWNTO 0);
      frame_written : OUT    std_logic ;
      write_out     : OUT    std_logic ;
      xw            : OUT    std_logic_vector (7 DOWNTO 0);
      yw            : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c5_t4_display_logic_top_level USE ENTITY alien_game_lib.c5_t4_display_logic_top_level;
   FOR ALL : c5_t4_game_logic_top_level USE ENTITY alien_game_lib.c5_t4_game_logic_top_level;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : c5_t4_display_logic_top_level
      PORT MAP (
         clk           => clk,
         frame_written => frame_written,
         pixd_in       => color,
         rst_n         => rst_n,
         write         => write_out,
         xw            => xw,
         yw            => yw,
         channel       => channel,
         lat           => lat,
         s_clk         => s_clk,
         s_rst         => s_rst,
         s_sda         => s_sda,
         sb            => sb,
         w_rdy         => w_rdy
      );
   U_0 : c5_t4_game_logic_top_level
      PORT MAP (
         btn           => btn,
         clk           => clk,
         rst_n         => rst_n,
         sw0           => sw0,
         w_rdy         => w_rdy,
         color         => color,
         frame_written => frame_written,
         write_out     => write_out,
         xw            => xw,
         yw            => yw
      );

END struct;
