-- VHDL Entity alien_game_lib.user_input.symbol
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-711-SPC)
--          at - 17:16:20 16.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY user_input IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END user_input ;

--
-- VHDL Architecture alien_game_lib.user_input.struct
--
-- Created:
--          by - bdgitr.UNKNOWN (HTC219-711-SPC)
--          at - 17:32:54 16.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF user_input IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout6 : std_logic;
   SIGNAL dout7 : std_logic;
   SIGNAL dout8 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'split'
   SIGNAL mw_U_0temp_din : std_logic_vector(3 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout <= "111011111011110111000000";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout1 <= "111000000111101110000000";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout2 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout3 <= "10100000";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout4 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout5 <= "00001010";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout, dout1, dout6)
   BEGIN
      CASE dout6 IS
      WHEN '0' => color_BGR <= dout;
      WHEN '1' => color_BGR <= dout1;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(dout2, dout3, dout7)
   BEGIN
      CASE dout7 IS
      WHEN '0' => x_coord <= dout2;
      WHEN '1' => x_coord <= dout3;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(dout4, dout5, dout8)
   BEGIN
      CASE dout8 IS
      WHEN '0' => y_coord <= dout4;
      WHEN '1' => y_coord <= dout5;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'split'
   mw_U_0temp_din <= btn;
   u_0combo_proc: PROCESS (mw_U_0temp_din)
   VARIABLE temp_din: std_logic_vector(3 DOWNTO 0);
   BEGIN
      temp_din := mw_U_0temp_din(3 DOWNTO 0);
      dout8 <= temp_din(1);
      dout7 <= temp_din(2);
      dout6 <= temp_din(3);
   END PROCESS u_0combo_proc;

   -- Instance port mappings.

END struct;
